FROM --platform=$BUILDPLATFORM node:18.16.1-alpine AS builder
RUN mkdir -p /app
WORKDIR /app
COPY --chown=node:node src src
COPY --chown=node:node package.json package-lock.json angular.json tsconfig.app.json tsconfig.json tsconfig.spec.json .npmrc ./
RUN npm install
RUN npm run build
FROM nginx:1.25
EXPOSE 80
COPY conf/default.conf /etc/nginx/conf.d/
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder app/dist/identity-manager /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
